[project]
name = "ogu-bop-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.1",
    "matplotlib-fontja>=1.1.0",
    "streamlit>=1.45.0",
]
